# Generated by Django 4.1 on 2023-10-29 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datos", "0002_alter_expense_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="expense",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Cash", "Cash"),
                    ("Card", "Card"),
                    ("Credit", "Credit"),
                    ("Airtel Money", "Airtel Money"),
                    ("MTN Money", "MTN Money"),
                    ("Other", "Other"),
                ],
                max_length=30,
                null=True,
            ),
        ),
    ]
