# Generated by Django 4.1 on 2023-10-31 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("datos", "0003_alter_expense_amount_alter_expense_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Income",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("date", models.DateField(blank=True, null=True)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Cash", "Cash"),
                            ("Card", "Card"),
                            ("Credit", "Credit"),
                            ("Airtel Money", "Airtel Money"),
                            ("MTN Money", "MTN Money"),
                            ("Other", "Other"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "category_name",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="datos.category",
                    ),
                ),
                (
                    "company_name",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="datos.supplier",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Income",},
        ),
    ]
